### ISSUE TITLE
Menu bar becomes unresponsive when hovering Toolbar menus [M641597]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#72] opened 2015-08-09 21:48 UTC
```
* This is a startup crash or failure to start (Y/N): N

* This is a fault of JavaScript acceleration (Y/N): (Use the steps above to
find out. Do NOT report if it is not.) N

* What steps are necessary to reproduce the bug? These must be reasonably 
reliable.

If you have the Bookmarks Toolbar and/or the Web Developer Toolbar (anything 
with submenus/folders), you can hover these left and right when they are open. 
See the video below, I don't know a better way to describe this. If you do this 
for a while (about 10 times right and left), the TFF Menu bar (including the 
Apple menu) stops working until you restart TFF. Other applications are not 
affected. When I rightclick the nonworking Menu bar, I get a contextual menu 
that I should get when rightclicking a toolbar in the browser window. I made a 
reduced testcase bookmarks file with only empty folders.

* Describe your processor, computer, operating system and any special
things about your environment.

PowerBook G4 1.33 GHz (7450), 10.5.8

* Include any useful additional information, steps you have tried, etc.:

attached testcase bookmarks file.
video (how to trigger the bug): http://www.youtube.com/watch?v=l7H1Conr42U

Additional information:
Machine: PowerBook G4 1.33 GHz (7450), 10.5.8
Created new OS X user account for testing; there are no haxies installed on 
this machine
The content of the folders in the toolbar doesn't matter, they can even be empty
It doesn't matter if nanojit for chrome is enabled or not.
It also happens in TFF 4.0.2., but not in Seamonkey 2.0.x
It doesn't seem to happen on G3 with 10.4.11 (at least I was unable to trigger 
it)
It does happen reliably on G4 with 10.5 (but I don't know if it's the processor 
type or the OS)
I don't know if this is a TFF, Mozilla, or OS X bug 

```

Original issue reported on code.google.com by `chtru...@web.de` on 21 Jun 2011 at 12:57

Attachments:
- [bookmarks.html](https://storage.googleapis.com/google-code-attachments/tenfourfox/issue-72/comment-0/bookmarks.html)

**Comment by classilla** [comment] 2017-06-30 04:18
Reopened as "regressed" in FPR1 (most likely it had just been wallpapered).

Current speculative fix idea is to just close the drop down popup when moving the mouse off. @chris-chtrusch , what do you think of that? Would that be annoying?

**Comment by chris-chtrusch** [comment] 2017-06-30 07:01
I'm not sure. We might get more complaints about unexpected UI behavior than we would have about the actual bug. Maybe first give it a shot in the next beta and see if it fixes the bug at all?

Is there a way to get hold of a debug build to see what's happening in the browser when the bug is triggered? Anything to look for in the console or browser toolbox (the one than can debug the browser's own JS with remote access)?

**Comment by chris-chtrusch** [comment] 2017-07-29 12:52
Log from debug build with comments.
[issue72 console.pdf](https://github.com/classilla/tenfourfox/files/1184958/issue72.console.pdf)

**Comment by classilla** [comment] 2017-07-29 19:23
It looks like that whole code segment is being triggered as a fall through with the popup open, so I'll probably need to put more debugging lines in there to figure it out. However, it does not seem to be caught by the solution for issue 248 and it should be unless it's not a mousedown that is being misdelivered.

**Comment by chris-chtrusch** [comment] 2017-08-06 14:19
Log from debug build for FPR2 (release version) with comments.
[issue72 console with TenFourFoxDebug-FPR2.pdf](https://github.com/classilla/tenfourfox/files/1203144/issue72.console.with.TenFourFoxDebug-FPR2.pdf)

**Comment by classilla** [comment] 2017-08-07 05:42
Event type 5 is `NSMouseMoved`. I guess that makes sense.

**Comment by classilla** [comment] 2017-08-07 05:49
One idea I have is to move the check for menubar clicks being misdelivered to the top of the event routine. Then it doesn't matter if the target is shot or not. Do other clicks in the window still work when this happens?

**Comment by chris-chtrusch** [comment] 2017-08-07 19:26
Yes, inside the application window everything works as it should when the bug has been triggered.

**Comment by classilla** [comment] 2017-09-04 01:50
Based on that I think I have a speculative fix (and I added some more debugging info in case that fails as well). I'm checking it doesn't regress anything and if not it will be in the next beta.

**Comment by classilla** [comment] 2017-09-09 03:26
Chris, are you still able to trigger the bug, or is it fixed now?

**Comment by chris-chtrusch** [comment] 2017-09-09 05:42
I can still triger it it FPR3b1. Going to try with the debug build this weekend.

**Comment by chris-chtrusch** [comment] 2017-09-09 10:09
Log from debug build for FPR3b1 with comments. This time a complete cycle from startup to quit.
[issue72.console.with.TenFourFoxDebug-FPR3b1.pdf](https://github.com/classilla/tenfourfox/files/1289680/issue72.console.with.TenFourFoxDebug-FPR3b1.pdf)

**Comment by classilla** [comment] 2017-09-09 16:37
That's obnoxious. It looks like the problem is in a different area of code entirely.

**Comment by classilla** [comment] 2017-09-09 16:43
So this is very strange. When the bug triggers, let me clarify something from your trace: does `trying to deliver this event too (1)` appear when you click on the menu bar? If you have the Console window open, does that immediately appear every time you click? Is it always followed by `don't know this event type (1)! sending to super`?

Event type 1 is `NSLeftMouseDown` and that should have been intercepted by the fix for issue #248.

**Comment by chris-chtrusch** [comment] 2017-09-09 19:44
If the bug is triggered, one click on the menu bar immediately produces exactly one instance of "trying to deliver this event too (1)" followed by "don't know this event type (1)! sending to super". 

If I click on the menu bar every ten seconds and do nothing else, the log looks like this (attachment).
[issue72.console.with.TenFourFoxDebug-FPR3b1(2).pdf](https://github.com/classilla/tenfourfox/files/1290063/issue72.console.with.TenFourFoxDebug-FPR3b1.2.pdf)

**Comment by chris-chtrusch** [comment] 2017-09-10 11:06
BTW, the situation can still be remedied by right-clicking the tab bar and choosing Customize from the context menu, then exiting Customize. Likewise by simply closing the browser window. The old method (toggle tabs on top) istn't an option anymore, of course. Here's what happens when I click Customize.
[issue72.console.with.TenFourFoxDebug-FPR3b1(3).pdf](https://github.com/classilla/tenfourfox/files/1290449/issue72.console.with.TenFourFoxDebug-FPR3b1.3.pdf)

**Comment by classilla** [comment] 2017-09-25 00:49
I've rewritten the debug code that emits the `don't know this event type` message to give a Y location for the click, since the handler for #248 (which should handle this for the top menu) is failing.

**Comment by chris-chtrusch** [comment] 2017-09-25 09:13
Looks like this in FPR3 final:

2017/09/25 11:03:00  [0x0-0xf37f37].com.floodgap.tenfourfoxdebug trying to deliver this event too (1) 
2017/09/25 11:03:00  [0x0-0xf37f37].com.floodgap.tenfourfoxdebug don't know this event type (1) (y=136.000000)! sending to super 

Do you need the full log?

**Comment by classilla** [comment] 2017-09-25 13:12
No, but what I do need to know is if the Y-location is always 136 (or within a 22-pixel range including that value, which would be the menu bar). Does it change based on where you click? Does it change relative to screen resolution or the position of the window?

**Comment by chris-chtrusch** [comment] 2017-09-25 15:32
The y location depends on where I click in the menu bar. Clicking a bit lower in the menu bar gives a slightly higher value (and vive versa), obviously corresponding to pixels.

The y location value also depends on the position of the browser window at the time the bug is triggered:
•Window at default position (fresh profile): values between 127 and 145
•Window a bit lower on screen: values between 163 and 181
•Window a lot lower: values between 350 and 368
(Changing the window position *after* the bug was triggered makes no difference in the y position.)

Screen resolution: If the bug triggers and I then switch to a lower screen resolution, the menu bar becomes responsive again (!) Not so, however, if I switch to a higher resolution, e.g. triggering it at 1024x768 and then switching to 1440x900.

**Comment by classilla** [comment] 2017-09-25 19:47
This is very clearly an OS bug that we've somehow managed to trigger, but those values are so all over the place I'm not sure how to work around it now. The Tiger problem was very easy to fix once it was obvious the clicks were somewhere a window couldn't possibly ever be. Here, however, the Y value being reported is actually truly within the content area. I may have to have some sort of CGEventTap to get the raw coordinates and that's going to be an ugly fix.

**Comment by chris-chtrusch** [comment] 2017-09-26 06:43
In this case it might be preferable to try your solution from comment 
https://github.com/classilla/tenfourfox/issues/72#issuecomment-312171041
so that we don't trigger the bug in the first place. I.e., either close the drop-down menu when moving the mouse off and don't open the next one automatically, or (better) leave the drop-down open until you click on the next one (like Safari).

**Comment by classilla** [comment] 2017-09-26 13:25
That's going to be my fallback, but my first pass will be to see if I can recover the original CG(S)Event and if it is similarly affected.

**Comment by classilla** [comment] 2017-10-21 06:09
Okay, I think I have something that works. I was able to trigger the bug on a debug build with my 10.5 DLSD PowerBook and have the code intercept and retarget the menu event.

There are actually two OS bugs occurring simultaneously. The first one appears to happen when the OS gets overwhelmed with top level events from Firefox/TenFourFox's popup windows. (There are many bugs like this with popup windows, such as bug 443178 which gave me a clue as to the second OS bug in this issue, or bug 425556, which is a different fix which they ended up not using.) When this occurs, the event seems to get "stuck" and interferes with other top level events; I kept seeing the event type 15 over and over in the log.

The second OS bug is why I couldn't fix it right the first time and also why the fix for #248 didn't help here. The `CGEvent` that underlies the `NSEvent` we receive is actually verifiably wrong: the Y coordinate is window-relative, not screen-relative, so we can never determine that the click is on the menu bar this way. This isn't a problem normally because there is a whole lot of exception code in TenFourFox/Firefox for getting correct mouse positions, but only for certain specific event types, not all of them (and the browser never expected this to occur, so this specific case isn't checked for).

However, the fix for bug 443178 has a different way of getting the mouse position directly from the `NSEvent`. This version _is_ accurate, so we use that.

There is a slight drop in performance when the bug triggers because the stuck event repeats over and over. It harmlessly gets bounced to the super, which ignores it, but it still has to be handled. At least this way the menu bar still works.

I consolidated this fix with #248 because they both end up doing the same thing once the situation is detected, but because that bug is also very hard to trigger, I have kept the same code path (i.e., I reorganized it, but didn't change it). The `[NSEvent mousePosition]` method would be faster than what it does, and should work for both 10.4 and 10.5, so I might do this for FPR5 early so that I can test it a lot (it does happen on Tiger too, and I can trigger it with lots of keyboarding).

Anyway, you should be able to see `Menu event dropped by OS!` when this situation or #248 triggers in a debug build. Should be out early next week; I'm doing some last minute validation on something else before I run the entire build cycle for FPR4b1.

**Comment by chris-chtrusch** [comment] 2017-10-22 12:27
Sounds convincing. Because of the bureaucracy involved in two German ISPs quarrelling about the right to provide me with their services I haven't had a wired internet connection in my appartment for the last month. It may take several weeks still before everything is settled. I'll try and download FPR4b1 anyway but it may take a bit longer than usual.

**Comment by chris-chtrusch** [comment] 2017-10-23 17:24
Menu bar stays responsive in FPR4b1, will verify with logs from debug build later.

**Comment by chris-chtrusch** [comment] 2017-10-26 17:52
Indeed I still see lots of "no target for this event (15)! sending to super" and the occasional "Menu event dropped by OS! (y=0.000000, type=1)" with the FPR4b1 debug build. So the bug is still present but the menu bar stays responsive as expected with this fix.

**Comment by classilla** [comment] 2017-10-27 04:33
Good, then that's at least good enough for now. I'll leave this open for the time being while I ensure #248 didn't get regressed. Assuming it didn't, I'll close this and open a tracking ticket to see if there's a better solution.

**Closed** 2017-10-30 04:29 UTC
Labels: auto-migrated, Mozilla, Priority-High, Type-Defect
